<?php

namespace BA\ParserBundle\Repository;

use BA\ParserBundle\Entity\Proxy;

/**
 * ProxyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProxyRepository extends \Doctrine\ORM\EntityRepository
{
    public function create()
    {
        return new Proxy();
    }
}
