<?php

namespace BA\ParserBundle\Repository;

use BA\ParserBundle\Entity\ProxyUse;

/**
 * ProxyUseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProxyUseRepository extends \Doctrine\ORM\EntityRepository
{
    public function create()
    {
        return new ProxyUse();
    }
}
