<?php

namespace BA\ParserBundle\Repository;

use BA\ParserBundle\Entity\UserAgent;

/**
 * UserAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAgentRepository extends \Doctrine\ORM\EntityRepository
{
    public function create()
    {
        return new UserAgent();
    }
}
